@echo off
REM Complete End-to-End Processing Pipeline
setlocal

echo.
echo ================================================================================
echo                      COMPLETE PROCESSING PIPELINE
echo ================================================================================
echo.
echo This will run the complete KPI processing pipeline:
echo 1. Validate configuration
echo 2. Run baseline processing
echo 3. Run incremental processing
echo 4. Generate final summary
echo.

set /p confirm="Continue with complete pipeline? (y/n): "
if /i not "%confirm%"=="y" exit /b 0

REM Check prerequisites
if not exist "config\kpi_config.yaml" (
    echo Error: Configuration file not found!
    pause
    exit /b 1
)

if not exist "data\consolidated_data.csv" (
    echo Error: Default data file not found!
    echo Available data files:
    dir /b data\*.csv 2>nul
    echo.
    echo Please ensure consolidated_data.csv exists or modify this script.
    pause
    exit /b 1
)

REM Create directories
if not exist "output" mkdir output
if not exist "logs" mkdir logs

echo.
echo ================================================================================
echo                      STEP 1: VALIDATE CONFIGURATION
echo ================================================================================
echo.
python scripts\config_validator_fixed.py --config config\kpi_config.yaml --data data\consolidated_data.csv

if %ERRORLEVEL% NEQ 0 (
    echo Configuration validation failed!
    pause
    exit /b 1
)

echo.
echo ================================================================================
echo                      STEP 2: BASELINE PROCESSING
echo ================================================================================
echo.
python scripts\complete_configurable_processor_fixed.py ^
    --config config\kpi_config.yaml ^
    --mode baseline ^
    --input data\consolidated_data.csv ^
    --output output\pipeline_baseline.json

if %ERRORLEVEL% NEQ 0 (
    echo Baseline processing failed!
    pause
    exit /b 1
)

echo.
echo ================================================================================
echo                     STEP 3: INCREMENTAL PROCESSING
echo ================================================================================
echo.
python scripts\complete_configurable_processor_fixed.py ^
    --config config\kpi_config.yaml ^
    --mode incremental ^
    --input data\consolidated_data.csv ^
    --output output\pipeline_incremental.json

if %ERRORLEVEL% NEQ 0 (
    echo Incremental processing failed!
    pause
    exit /b 1
)

echo.
echo ================================================================================
echo                       STEP 4: GENERATE SUMMARY
echo ================================================================================
echo.
python final_summary.py

echo.
echo ================================================================================
echo                      PIPELINE COMPLETED SUCCESSFULLY
echo ================================================================================
echo.
echo Results available in:
echo   • output\pipeline_baseline.json
echo   • output\pipeline_incremental.json
echo.
echo Summary generated by final_summary.py
echo.

pause
